[project]
name = "castillouparela-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gradio>=5.22.0",
    "openai>=1.68.2",
    "openai-agents>=0.0.15",
    "pdfplumber>=0.11.9",
    "pypdf>=5.4.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]